espoo-dev/med_system_backend

app/controllers/api/v1/medical_shifts_controller.rb
app/operations/medical_shifts/list.rb
spec/operations/medical_shifts/list_spec.rb

fix: remove unused parameter in the MedicalShifts listing operation

---

app/controllers/api/v1/procedures_controller.rb
app/models/procedure.rb
app/models/user.rb
app/operations/procedures/create.rb
app/serializers/procedure_serializer.rb
db/migrate/20240319125612_add_custom_to_procedures.rb
db/migrate/20240319131254_add_user_id_to_procedures.rb
db/schema.rb
spec/factories/procedures.rb
spec/models/procedure_spec.rb
spec/models/user_spec.rb
spec/operations/procedures/create_spec.rb

fix: #129 
- add `custom` field to `procedures` table.
- add `User` to `Procedures` and associate `user` with `procedure` when `custom` attribute is true.

feat: add custom field to procedures table

---

app/models/event_procedure.rb
db/migrate/20240329122823_change_room_type_and_urgency_in_event_procedures.rb
db/schema.rb
spec/operations/event_procedures/create_spec.rb
spec/requests/api/v1/event_procedures_request_spec.rb

refactor: remove the mandatory presence of the room_type and urgency columns in the event_procedures table

---

app/controllers/api/v1/health_insurances_controller.rb
app/models/health_insurance.rb
app/operations/health_insurances/list.rb
app/queries/health_insurances/by_custom_query.rb
spec/operations/health_insurances/list_spec.rb
spec/queries/health_insurances/by_custom_query_spec.rb

refactor: endpoint to return only health_insurances with the attribute custon=false by default

---

.rubocop.yml
lib/data/port_values/2008_5_edition.json
lib/data/procedures.csv
lib/data/procedures_test.csv
lib/scripts/create_cbhpm_procedures.rb
lib/scripts/persist_procedures.rb
lib/scripts/read_procedures_pdf.rb
lib/tasks/create_json_file.rake
lib/tasks/persist_in_database.rake
lib/tasks/port_values_2008.rake
spec/fixtures/batch_anesthetic_port_error.json
spec/fixtures/batch_test.json
spec/fixtures/batch_test_error.json
spec/requests/graphql/users_query_spec.rb
spec/tasks/create_json_file_spec.rb
spec/tasks/persist_in_database_spec.rb
spec/tasks/port_values_2008_spec.rb

Obs.: 
- The changes in `lib/data/procedures.csv` was made with @danielnottingham to remove invalid lines in csv file and fix two lines with correct code and port.
- Talking to @danielnottingham with agree to create a new script to persist cbhpm_procedures in the same process that procedures are created. That's why I needed to modify `Scripts::ReadProceduresPDF` to export a new attribute `anesthetic_port` in JSON file.
Steps to run rake:
1 - Run `rake port_values_2008:import`;
2 - Run `rake procedures:create_json_file["lib/data/procedures.csv",500]` to create JSON files with 500 lines from CSV file;
3 -  Run `rake procedures:persist_in_database["PATH JSON FILE"]` to persist procedures and cbhpm_procedures in database for each JSON file created in the last step.

Create rake to persist procedures

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/event_procedures_controller.rb
app/controllers/api/v1/hospitals_controller.rb
app/controllers/api/v1/patients_controller.rb
app/controllers/api/v1/procedures_controller.rb
app/controllers/concerns/respondable.rb
app/policies/application_policy.rb
app/policies/event_procedure_policy.rb
app/policies/medical_shift_policy.rb
app/policies/patient_policy.rb
app/policies/procedure_policy.rb
config/locales/api/v1/en.yml
spec/policies/application_policy_spec.rb
spec/policies/event_procedure_dashboard_policy_spec.rb
spec/policies/event_procedure_policy_spec.rb
spec/policies/health_insurance_policy_spec.rb
spec/policies/hospital_policy_spec.rb
spec/policies/patient_policy_spec.rb
spec/policies/procedure_policy_spec.rb
spec/policies/user_policy_spec.rb
spec/requests/api/v1/event_procedures_request_spec.rb
spec/requests/api/v1/hospitals_request_spec.rb
spec/requests/api/v1/patients_request_spec.rb
spec/requests/api/v1/procedures_request_spec.rb
spec/support/pundit.rb

- Change success message to delete endpoints and fix tests
- Add owner in policies to procedure_policy and patient_policy
- Obs.:
- There are 4 policies that need owner to update and delete endpoint: event_procedures_policy, medical_shifts_policy, procedures_policy, patients_policy. The models don't belong to user, so they can check `user == record.user`.
-  3 policies that don't have delete endpoint: event_procedure_dashboard_policy, health_insurance_policy, user_policy.
- Hospital_policy have delete action, but the models don't belong to user, so we can't check `user == record.user`.
- Add tests to all policies

Add standard pattern to delete endpoints

---

app/operations/health_insurances/list.rb
spec/operations/health_insurances/list_spec.rb
spec/requests/api/v1/health_insurances_request_spec.rb

Reverts espoo-dev/med_system_backend#239

Revert "Revert "Fixes the HealthInsurence#index to return true and false custom values.""

---

app/operations/health_insurances/list.rb
spec/requests/api/v1/health_insurances_request_spec.rb

- **Description**
Fixes HealthInsurance endpoint to return custom, not custom and seed health insurances when no Custom param is passed.
Closes #241

Fixes HealthInsurance endpoint to return custom and not custom values.

---

app/operations/event_procedures/build_total_amount_cents.rb

Refacts apartment_multiplier BuildTotalAmountCents on EventProcedures to use constants instead magic numbers.

Refacts apartment_multiplier to use constants instead magic numbers

---

app/operations/event_procedures/total_amount_cents.rb
spec/operations/event_procedures/total_amount_cents_spec.rb

- **Context**
Total/Paid/Unpaid values were not returning correctly for default procedures.
Total/Paid/Unpaid for default procedures were been calculating with procedures values, but it should be calculated with CbhpmProcedures and PortValues.
- **Solution**
Instead of doing the calculation for Total/Paid/Unpaid values on TotalAmountCents, use BuildTotalAmountCents, because its calcutales the values using CbhpmProcedures and PortValues.

Fix event procedure total amount cents filter

---

spec/requests/api/v1/event_procedures_dashboard_request_spec.rb
spec/requests/api/v1/event_procedures_request_spec.rb
spec/requests/api/v1/health_insurances_request_spec.rb
spec/requests/api/v1/hello_word_request_spec.rb
spec/requests/api/v1/hospitals_request_spec.rb
spec/requests/api/v1/medical_shifts_request_spec.rb
spec/requests/api/v1/patients_request_spec.rb
spec/requests/api/v1/pdf_reports_request_spec.rb
spec/requests/api/v1/procedures_request_spec.rb
spec/requests/api/v1/users_request_spec.rb
spec/support/shared_contexts/unauthenticated_user.rb

This task introduces a 'shared context' for handling unauthenticated user requests in request tests. Instead of repeating the same authentication failure checks, we now reuse the shared context across multiple tests,  for this was created shared_context 'when user is not authenticated'`.
fix #220

test: add shared context for unauthenticated access

---

app/controllers/api/v1/event_procedures_controller.rb
app/operations/event_procedures/list.rb
spec/operations/event_procedures/list_spec.rb
spec/requests/api/v1/event_procedures_request_spec.rb

- *Context*
Total/Paind/Unpaid values was considering the page param on the returning values.

Fixes total value on EventProcedure to return values without consider pages and per_page params

---

config/initializers/devise.rb

Fix #260 
- *Context*
Devise is currently trying to find a secret key in credentials, secrets and config before checking the application itself, deprecation warning is triggered on every call to Rails.application.secrets.
- *Solution*
Configure Devise's secret_key on setup.
https://github.com/heartcombo/devise/issues/5644

Fixes deprecation warning for Rails.application.secrets

---

Gemfile
Gemfile.lock

Fixes #261 
- *Context*
Warning generated: `DEPRECATION WARNING: DeprecatedConstantAccessor.deprecate_constant without a deprecator is deprecated`.
Devise shouldn't be using the DeprecatedConstantAccessor anymore, and instead should be using the Devise.deprecator which does not generate a Deprecation Warning. Described in https://github.com/heartcombo/devise/issues/5635
It was fixed on devise 4.9.3
https://github.com/heartcombo/devise/blob/v4.9.4/CHANGELOG.md#494---2024-04-10
- *Solution*
Upgrade Devise version to 4.9.4 (latest version)

Upgrade devise version from 4.9.2 to 4.9.4 to remove deprecation warning

---

docker-compose.yml

Fix #262 
- *Context*
Warning generated: `WARN[0000] /home/ferreira/Repositories/med_system_backend/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion`.
- *Solution*
Remove `version` attribute from docker-compose.yml.

Removes 'version' from docker-compose.yml to avoid warning

---

app/controllers/api/v1/event_procedures_controller.rb
app/controllers/api/v1/pdf_reports_controller.rb
app/pdfs/header_pdf.rb
db/seeds/02_procedures_default.rb
spec/pdfs/medical_shifts_report_pdf_spec.rb
spec/requests/api/v1/patients_request_spec.rb

Fix #263 
- *Context*
Test coverage is not 100%
- *Solution*
Adds specs to make sure that test coverage is 100%.

Adds specs to make sure that test coverage is 100%

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb

_Description_
- Fixed the login flow for users.
- Now after login, the user is redirected based on their role (admin or non-admin).
- Error messages are displayed correctly when login fails.
_Changes_
- Overridden after_sign_in_path_for method.
fix #211

Fixes user login redirection for admins and no admins

---

Gemfile
Gemfile.lock
config/environments/development.rb

Fix #276 
- *Context*
We need to configure a solution for handling emails in our development/test environment that allows us to view system-generated emails without actually sending them to real recipients.
- *Solution*
Configs Letter opener to visualize dev e-mails.
https://github.com/ryanb/letter_opener

Configs Letter Opener gem

---

spec/requests/api/v1/event_procedures_request_spec.rb
spec/requests/api/v1/hospitals_request_spec.rb
spec/requests/api/v1/medical_shifts_request_spec.rb
spec/requests/api/v1/patients_request_spec.rb
spec/requests/api/v1/procedures_request_spec.rb
spec/support/shared_contexts/successful_resource_delete.rb

_Context_
- Tests with patterns leading to code duplication.
_Solution_
- add a shared RSpec example for DELETE requests, the example validates the correct success message and response status for successful deletes.

feat: create shared example for delete request specs

---

app/queries/event_procedures/by_date_between.rb
config/initializers/administrate.rb
db/seeds.rb
lib/scripts/persist_procedures.rb
spec/models/event_procedure_spec.rb
spec/policies/hospital_policy_spec.rb
spec/policies/user_policy_spec.rb
spec/rails_helper.rb

We have identified that a minor update to RuboCop may have introduced new rules or changed the behavior of existing rules, impacting the project code.
_Changes:_
- Adjustments to the code style to follow the new rules
- No changes to logic or functionality
fix #296

fix: rubocop offences adjusted

---

config/environments/test.rb
spec/models/user_spec.rb
spec/requests/api/v1/users_request_spec.rb

Fix #292 
- *Context*
Enable Devise module Recoverable for Users.
- *Solution*
**Obs**: Recoverable module was enabled already.
Add specs for Recoverable.

Enable Devise Recoverable for Users

---

spec/models/event_procedure_spec.rb
spec/models/health_insurance_spec.rb
spec/models/hospital_spec.rb
spec/models/medical_shift_spec.rb
spec/models/patient_spec.rb
spec/models/procedure_spec.rb
spec/models/user_spec.rb
spec/support/shared_contexts/soft_delete.rb

_Context_
- soft delete behavior without test coverage
fix #304

feat: create shared example for soft delete

---

Gemfile
Gemfile.lock
config/initializers/rack_attack.rb
spec/rails_helper.rb

Fix #284 
- *Solution*
Configs Rack:Attack for:
1. Throttle Spammy Clients
2. Prevent Brute-Force Login Attacks

Configs Rack:Attack

---

app/assets/stylesheets/devise.css
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/locales/pt-BR/devise.yml

_Context_
- The pages were using the standard Devise templates, without customization
_Solution_
- creation of custom templates
fix #313

Added layout for login and registration page

---

.gitignore
app/models/user.rb
db/migrate/20250528125806_add_lockable_to_users.rb
db/schema.rb

Fix #283 
- *Solution*
Enables Lockable Devise module.
Creates migration to add lockable required fields.

Configs Devise module Lockable

---

Gemfile
Gemfile.lock
app/controllers/api/v1/event_procedures_controller.rb
app/models/event_procedure.rb
app/operations/event_procedures/list.rb
config/environments/development.rb
spec/factories/event_procedures.rb
spec/operations/event_procedures/list_spec.rb
spec/support/query_helper.rb

_Context_
- The index action of the EventProceduresController controller was generating an N+1 query when accessing the port_values association through cbhpm.
_Solution_
- The port_values association has been added to the EventProcedures::List service. This means the association is loaded along with the others (procedure, patient, hospital, health_insurance) in a single query, avoiding the N+1 problem.
Fix #325

Fix to query n+1 in eventprocedure
