espoo-dev/med_system_backend

- app/models/hospital.rb
- db/migrate/20231210191319_create_hospital.rb
- db/schema.rb
- spec/factories/hospitals.rb
- spec/models/hospital_spec.rb
> Create Hospital model

- app/models/hospital.rb
- app/models/patient.rb
- db/migrate/20231210191319_create_hospital.rb
- db/migrate/20231210192627_create_patients.rb
- db/schema.rb
- spec/factories/patients.rb
- spec/models/hospital_spec.rb
- spec/models/patient_spec.rb
> Create Patient model

- app/models/health_insurance.rb
- db/migrate/20231211224249_create_health_insurances.rb
- db/schema.rb
- spec/factories/health_insurances.rb
- spec/models/health_insurance_spec.rb
> create health insurance model

- app/models/procedure.rb
- db/migrate/20231212152613_create_procedures.rb
- db/schema.rb
- spec/factories/procedures.rb
- spec/models/procedure_spec.rb
> feat: added Procedure model

- app/controllers/api/v1/procedures_controller.rb
- app/policies/procedure_policy.rb
- app/serializers/procedure_serializer.rb
- config/routes.rb
- spec/requests/api/v1/procedures_request_spec.rb
- swagger/v1/swagger.yaml
> feat: Added endpoint to list procedures

- app/controllers/api/v1/api_controller.rb
- spec/requests/api/v1/procedures_request_spec.rb
- spec/requests/api/v1/users_request_spec.rb
- spec/support/devise.rb
> fix: endpoints to list users and procedures

- Gemfile
- Gemfile.lock
- app/enumerations/event_procedures/room_types.rb
- app/models/application_record.rb
- app/models/concerns/monetizable.rb
- app/models/event_procedure.rb
- config/initializers/money.rb
- db/migrate/20231215190200_create_event_procedures.rb
- db/schema.rb
- spec/factories/event_procedures.rb
- spec/models/event_procedure_spec.rb
> feat: create EventProcedure, added Money and Enumerate_it gems

- app/controllers/api/v1/event_procedures_controller.rb
- app/models/event_procedure.rb
- app/policies/event_procedure_policy.rb
- app/serializers/event_procedure_serializer.rb
- config/routes.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> feat: Added enpoint to list event_procedures

- spec/support/shoulda_matchers.rb
- swagger/v1/swagger.yaml
> refactor: reorganize swagger.yml

- app/models/health_insurance.rb
- app/models/hospital.rb
- app/models/patient.rb
- app/models/procedure.rb
- spec/models/health_insurance_spec.rb
- spec/models/hospital_spec.rb
- spec/models/patient_spec.rb
- spec/models/procedure_spec.rb
> refactor: rearrange and/or correct model specs

- app/models/procedure.rb
- db/migrate/20231222205030_add_amount_and_description_to_procedures.rb
- db/schema.rb
- spec/factories/procedures.rb
- spec/models/procedure_spec.rb
> feat: add amount and description to procedures

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/event_procedures_controller.rb
- app/models/event_procedure.rb
- app/operations/event_procedures/create.rb
- app/policies/event_procedure_policy.rb
- app/serializers/event_procedure_serializer.rb
- app/serializers/health_insurance_serializer.rb
- app/serializers/hospital_serializer.rb
- app/serializers/patient_serializer.rb
- app/serializers/procedure_serializer.rb
- config/routes.rb
- db/migrate/20231226165615_remove_amount_cents_from_event_procedures.rb
- db/schema.rb
- lib/generators/operation/operation_generator.rb
- lib/generators/operation/templates/operation.erb
- lib/generators/operation/templates/spec.erb
- spec/factories/event_procedures.rb
- spec/models/event_procedure_spec.rb
- spec/operations/event_procedures/create_spec.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
- swagger/v1/swagger.yaml
> feat: allow create event_procedure

- app/controllers/api/v1/event_procedures_controller.rb
- app/operations/event_procedures/destroy.rb
- app/operations/event_procedures/find.rb
- app/operations/event_procedures/update.rb
- app/policies/event_procedure_policy.rb
- config/database.yml
- config/routes.rb
- spec/operations/event_procedures/destroy_spec.rb
- spec/operations/event_procedures/find_spec.rb
- spec/operations/event_procedures/update_spec.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> feat: allow update and destroy event procedure

- app/controllers/api/v1/procedures_controller.rb
- app/operations/procedures/create.rb
- app/policies/procedure_policy.rb
- config/routes.rb
- spec/operations/procedures/create_spec.rb
- spec/requests/api/v1/procedures_request_spec.rb
> feat: allow create procedure

- app/controllers/api/v1/hospitals_controller.rb
- app/policies/hospital_policy.rb
- app/serializers/hospital_serializer.rb
- config/routes.rb
- spec/requests/api/v1/hospitals_request_spec.rb
> feat: allow listing of hospitals

- app/controllers/api/v1/hospitals_controller.rb
- app/operations/hospitals/create.rb
- app/operations/hospitals/destroy.rb
- app/operations/hospitals/find.rb
- app/operations/hospitals/update.rb
- app/policies/hospital_policy.rb
- config/routes.rb
- spec/operations/hospitals/create_spec.rb
- spec/operations/hospitals/destroy_spec.rb
- spec/operations/hospitals/find_spec.rb
- spec/operations/hospitals/update_spec.rb
- spec/requests/api/v1/hospitals_request_spec.rb
> feat: allows to create update and destroy hospitals

- app/controllers/api/v1/event_procedures_controller.rb
- app/controllers/api/v1/hospitals_controller.rb
- app/controllers/api/v1/patients_controller.rb
- app/controllers/api/v1/procedures_controller.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
- spec/requests/api/v1/hospitals_request_spec.rb
- spec/requests/api/v1/patients_request_spec.rb
- spec/requests/api/v1/procedures_request_spec.rb
> refactor: improve error payload for endpoints

- app/controllers/api/v1/event_procedures_controller.rb
- app/operations/event_procedures/calculate_total_amount.rb
- app/operations/event_procedures/calculate_total_amount_payd.rb
- app/operations/event_procedures/calculate_total_amount_unpayd.rb
- app/operations/event_procedures/list.rb
- app/operations/event_procedures/total_amount_cents.rb
- app/serializers/event_procedure_serializer.rb
- spec/operations/event_procedures/calculate_total_amount_payd_spec.rb
- spec/operations/event_procedures/calculate_total_amount_spec.rb
- spec/operations/event_procedures/calculate_total_amount_unpayd_spec.rb
- spec/operations/event_procedures/list_spec.rb
- spec/operations/event_procedures/total_amount_cents_spec.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> feat: updated payload for list event_procedures

- app/operations/event_procedures/list.rb
- spec/operations/event_procedures/list_spec.rb
> refactor: returns the list of event_procedures ordered by most recent

- app/controllers/api/v1/event_procedures_controller.rb
- app/operations/event_procedures/list.rb
- spec/operations/event_procedures/list_spec.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> feat: allows you to filter event_procedures by month and by payd

- app/enumerations/medical_shifts/workloads.rb
- app/models/hospital.rb
- app/models/medical_shift.rb
- db/migrate/20240129135123_create_medical_shifts.rb
- db/schema.rb
- spec/enumarations/event_procedures/room_types_spec.rb
- spec/enumarations/medical_shifts/workloads_spec.rb
- spec/factories/medical_shifts.rb
- spec/models/hospital_spec.rb
- spec/models/medical_shift_spec.rb
> feat: added the MedicalShifts model

- app/operations/event_procedures/update.rb
- spec/operations/event_procedures/update_spec.rb
fixes the event_procedure update operation that did not update the total_amount_cents attribute
> fix: fix event_procedure update operation

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/list.rb
- app/policies/medical_shift_policy.rb
- app/serializers/medical_shift_serializer.rb
- config/database.yml
- config/routes.rb
- spec/operations/medical_shifts/list_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
- spec/support/bullet.rb
> feat: added endpoint to list medical shifts

- app/models/event_procedure.rb
- app/models/medical_shift.rb
- app/operations/event_procedures/list.rb
- app/operations/medical_shifts/list.rb
- app/queries/application_query.rb
- app/queries/event_procedures/by_month_query.rb
- app/queries/event_procedures/by_payd_query.rb
- app/queries/medical_shifts/by_hospital_query.rb
- app/queries/medical_shifts/by_month_query.rb
- app/queries/medical_shifts/by_payd_query.rb
- spec/queries/application_query_spec.rb
- spec/queries/event_procedures/by_month_query_spec.rb
- spec/queries/event_procedures/by_payd_query_spec.rb
- spec/queries/medical_shifts/by_hospital_query_spec.rb
- spec/queries/medical_shifts/by_month_query_spec.rb
- spec/queries/medical_shifts/by_payd_query_spec.rb
> feat: added query objects to medical_shift and event_procedure

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/create.rb
- app/policies/medical_shift_policy.rb
- config/routes.rb
- spec/operations/medical_shifts/create_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> feat: allows you to create MedicalShift

- .reek.yml
- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/total_amount_cents.rb
- app/queries/medical_shifts/sum_payd_amount_query.rb
- app/queries/medical_shifts/sum_total_amount_query.rb
- app/queries/medical_shifts/sum_unpaid_amount_query.rb
- app/serializers/medical_shift_serializer.rb
- spec/operations/medical_shifts/total_amount_cents_spec.rb
- spec/queries/medical_shifts/sum_payd_amount_query_spec.rb
- spec/queries/medical_shifts/sum_total_amount_query_spec.rb
- spec/queries/medical_shifts/sum_unpaid_amount_query_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> feat: add the total sum, paid and unpaid to the medical_shifts listing

- app/controllers/api/v1/medical_shifts_controller.rb
- app/models/medical_shift.rb
- app/models/user.rb
- app/operations/medical_shifts/create.rb
- app/operations/medical_shifts/list.rb
- app/operations/medical_shifts/total_amount_cents.rb
- app/queries/medical_shifts/sum_payd_amount_query.rb
- app/queries/medical_shifts/sum_total_amount_query.rb
- app/queries/medical_shifts/sum_unpaid_amount_query.rb
- db/migrate/20240206181632_add_user_id_to_medical_shifts.rb
- db/schema.rb
- spec/factories/medical_shifts.rb
- spec/models/medical_shift_spec.rb
- spec/models/user_spec.rb
- spec/operations/medical_shifts/create_spec.rb
- spec/operations/medical_shifts/list_spec.rb
- spec/operations/medical_shifts/total_amount_cents_spec.rb
- spec/queries/medical_shifts/sum_payd_amount_query_spec.rb
- spec/queries/medical_shifts/sum_total_amount_query_spec.rb
- spec/queries/medical_shifts/sum_unpaid_amount_query_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> feat: added user to medical_shifts table

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/list.rb
- app/policies/medical_shift_policy.rb
- spec/operations/medical_shifts/list_spec.rb
- spec/policies/application_policy_spec.rb
- spec/policies/medical_shift_policy_spec.rb
> refactor: added the Scope class to the MedicalShiftPolicy

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/find.rb
- app/operations/medical_shifts/update.rb
- app/policies/medical_shift_policy.rb
- config/routes.rb
- spec/operations/medical_shifts/find_spec.rb
- spec/operations/medical_shifts/update_spec.rb
- spec/policies/medical_shift_policy_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> feat: allows updating medical_shifts

- app/controllers/api/v1/procedures_controller.rb
- app/operations/procedures/list.rb
- spec/operations/procedures/list_spec.rb
> feat: sort the listing in descending order of Procedures

- app/controllers/api/v1/event_procedures_controller.rb
- app/operations/event_procedures/list.rb
- spec/operations/event_procedures/list_spec.rb
> fix: remove unused parameter in the Events Procedures listing operation

- app/models/procedure.rb
- db/migrate/20240304222146_add_unique_constraint_to_procedures_code.rb
- db/migrate/20240304224525_change_code_to_citext_in_procedures.rb
- db/schema.rb
- db/seeds/procedures.rb
- spec/factories/procedures.rb
- spec/models/procedure_spec.rb
> fix: added unique validation to code attribute for Procedure

- db/migrate/20240305090644_change_name_and_address_to_citext_in_hospitals.rb
- db/schema.rb
- spec/models/hospital_spec.rb
> fix: uniqueness validation of name and address for Hospital

- Gemfile
- Gemfile.lock
- config/initializers/sentry.rb
> Setup Sentry

- app/controllers/api/v1/api_controller.rb
- app/models/patient.rb
- spec/models/patient_spec.rb
- spec/requests/api/v1/patients_request_spec.rb
> Do not allow to delete patient with event procedure associated

- Gemfile
- app/controllers/api/v1/patients_controller.rb
- app/models/patient.rb
- app/serializers/patient_serializer.rb
- config/initializers/sentry.rb
- spec/models/patient_spec.rb
- spec/requests/api/v1/patients_request_spec.rb
> Add deletable to patient

- app/operations/event_procedures/list.rb
- config/database.yml
- spec/operations/event_procedures/list_spec.rb
> refactor: sort event_procedures by date desc

- .rubocop.yml
- app/controllers/api/v1/event_procedures_controller.rb
- app/dashboards/event_procedure_dashboard.rb
- app/serializers/event_procedure_serializer.rb
- db/migrate/20231215190200_create_event_procedures.rb
- db/migrate/20240313131402_add_payd_to_event_procedure.rb
- db/schema.rb
- db/seeds.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> 123 add payd to event_procedure

- app/controllers/api/v1/event_procedures_controller.rb
- db/seeds.rb
Reverts espoo-dev/med_system_backend#126
> Revert "update event_procedures payd_at"

- app/controllers/api/v1/event_procedures_dashboard_controller.rb
- app/operations/event_procedures/dashboard_amount_by_day.rb
- spec/requests/api/v1/event_procedures_dashboard_request_spec.rb
> Filter event_procedures_dashboard by user_id

- app/controllers/api/v1/event_procedures_controller.rb
- app/enumerations/event_procedures/payments.rb
- app/models/event_procedure.rb
- app/serializers/event_procedure_serializer.rb
- db/migrate/20240319112216_add_payment_to_event_procedures.rb
- db/schema.rb
- spec/enumarations/event_procedures/payments_spec.rb
- spec/factories/event_procedures.rb
- spec/models/event_procedure_spec.rb
- spec/operations/event_procedures/create_spec.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> feat: add payment field to event_procedures table

- app/controllers/api/v1/health_insurances_controller.rb
- app/models/health_insurance.rb
- app/models/user.rb
- app/operations/health_insurances/create.rb
- app/serializers/health_insurance_serializer.rb
- db/migrate/20240325122604_add_custom_to_health_insurances.rb
- db/migrate/20240325123343_add_user_id_to_health_insurances.rb
- db/schema.rb
- spec/factories/health_insurances.rb
- spec/models/health_insurance_spec.rb
- spec/models/user_spec.rb
- spec/operations/health_insurances/create_spec.rb
- spec/requests/api/v1/health_insurances_request_spec.rb
> feat: add custom field to health_insurances table

- app/controllers/api/v1/procedures_controller.rb
- app/models/procedure.rb
- app/operations/procedures/list.rb
- app/queries/procedures/by_custom_query.rb
- spec/operations/procedures/list_spec.rb
- spec/queries/procedures/by_custom_query_spec.rb
> feat: add filter by custom and returns all procedures custom false by default

- app/controllers/api/v1/event_procedures_controller.rb
- app/models/event_procedure.rb
- app/models/health_insurance.rb
- app/models/procedure.rb
- app/operations/event_procedures/create.rb
- app/operations/health_insurances/find_or_create.rb
- spec/factories/event_procedures.rb
- spec/models/event_procedure_spec.rb
- spec/models/health_insurance_spec.rb
- spec/models/procedure_spec.rb
- spec/operations/event_procedures/create_spec.rb
- spec/operations/health_insurances/find_or_create_spec.rb
- spec/operations/procedures/find_or_create_spec.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> feat: allows you to create a HealthInsurance together with a EventProcedure

- app/models/hospital.rb
- db/migrate/20240411142121_remove_uniqueness_constraint_of_address_on_hospitals.rb
- db/schema.rb
- spec/models/hospital_spec.rb
> refactor: removes uniqueness validation from the Hospital address

- app/serializers/event_procedure_serializer.rb
- db/seeds.rb
- spec/requests/api/v1/event_procedures_request_spec.rb
> 158 add observation and value to list event procedures endpoint

- app/dashboards/event_procedure_dashboard.rb
- app/dashboards/health_insurance_dashboard.rb
- app/dashboards/hospital_dashboard.rb
- app/dashboards/patient_dashboard.rb
- app/dashboards/procedure_dashboard.rb
- app/dashboards/user_dashboard.rb
- app/models/health_insurance.rb
- db/migrate/20240423134905_add_unique_index_to_health_insuarnces.rb
- db/schema.rb
- spec/models/health_insurance_spec.rb
> refacto: does not allow create HealthInsurance with the same name per user

- .env.example
- bin/dev
- config/database.yml
> Fix settings on database.yml and bin/dev

- app/models/cbhpm.rb
- app/models/port_value.rb
- db/migrate/20240511140008_create_port_values.rb
- db/schema.rb
- spec/factories/port_values.rb
- spec/models/cbhpm_spec.rb
- spec/models/port_value_spec.rb
> feat: create port_value model

- app/models/patient.rb
- db/migrate/20240713155011_update_patients_names.rb
- spec/models/patient_spec.rb
> Trim patient name

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/destroy.rb
- app/policies/medical_shift_policy.rb
- config/routes.rb
- db/schema.rb
- spec/operations/medical_shifts/destroy_spec.rb
- spec/policies/medical_shift_policy_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
- spec/support/pundit.rb
> Add delete endpoint for medical shifts

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/hospital_name_suggestion.rb
- spec/operations/medical_shifts/hospital_name_suggestion_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> fix: medical shifts adjust policy and authorization

- .rubocop.yml
- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/total_amount_cents.rb
- app/queries/medical_shifts/sum_payd_amount_query.rb
- app/queries/medical_shifts/sum_total_amount_query.rb
- app/queries/medical_shifts/sum_unpaid_amount_query.rb
- config/routes.rb
- spec/operations/medical_shifts/hospital_name_suggestion_spec.rb
- spec/operations/medical_shifts/total_amount_cents_spec.rb
- spec/queries/medical_shifts/sum_payd_amount_query_spec.rb
- spec/queries/medical_shifts/sum_total_amount_query_spec.rb
- spec/queries/medical_shifts/sum_unpaid_amount_query_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> 217 - Filter sumary data by month at medical shift index

- app/controllers/api/v1/medical_shifts_controller.rb
- app/operations/medical_shifts/amount_suggestion.rb
- app/operations/medical_shifts/hospital_name_suggestion.rb
- app/policies/medical_shift_policy.rb
- config/routes.rb
- spec/operations/medical_shifts/amount_suggestion_spec.rb
- spec/requests/api/v1/medical_shifts_request_spec.rb
> 219 add endpoint to get medical shift values suggestions

- app/operations/medical_shifts/list.rb
- spec/operations/medical_shifts/list_spec.rb
-  Change order by for start_date
> fix: medical shifts order by start date

- docker-compose.yml
Adds run rails server command to dockerfile. Now, the servers logs is on docker terminal.
> Adds run server command to dockerfile.

- config/initializers/prawn.rb
- lib/tasks/persist_in_database.rake
- lib/tasks/port_values_2008.rake
- spec/tasks/persist_in_database_spec.rb
- spec/tasks/port_values_2008_spec.rb
> fix: remove prints from RSpec

- Gemfile
- Gemfile.lock
- app/models/user.rb
- config/environments/test.rb
- config/initializers/devise_async.rb
- config/initializers/rack_attack.rb
- spec/models/user_spec.rb
Reverts espoo-dev/med_system_backend#318
> Revert "Feat Devise Async"
